version: "3.4"

services:
  php:
    image: laravel
    container_name: laravel-container
    build:
      context: .
      dockerfile: Docker/laravel/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./local.laravel-auth:/var/www/local.laravel-auth:cached
  db:
    image: db
    container_name: db-container
    build:
      context: .
      dockerfile: Docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel-db
      MYSQL_USER: laravel-user
      MYSQL_PASSWORD: laravel-password
